services:
  db:
    image: postgres:16
    container_name: reserve-crm-db
    environment:
      POSTGRES_USER: reserve_crm
      POSTGRES_PASSWORD: reserve_crm_password
      POSTGRES_DB: reserve_crm
    ports:
      - "5432:5432"
    volumes:
      - reserve_crm_db_data:/var/lib/postgresql/data

volumes:
  reserve_crm_db_data:
